modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/soramame0256/showmemydps/issues"
license = "All Rights Reserved"

[[mods]]
modId = "showmemydps"
version = "${version}"
displayName = "ShowMeMyDPS!"
authors = "soramame_256"
description = '''
A Simple Mod that shows you damage result
'''
#logoFile = ""

[[dependencies.showmemydps]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.showmemydps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "CLIENT"
