modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/soramame0256/showmemydps/issues"
license = "MIT license"

[[mods]]
modId = "showmemydps"
version = "${version}"
displayName = "ShowMeMyDPS!"
authors = "soramame_256"
description = '''
A Simple Mod that shows you damage result
'''
#logoFile = ""

[[dependencies.showmemydps]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.showmemydps]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config="showmemydps-common.mixins.json"

